////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by libevhtp.py. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __hustdb_handler_frame_20160413174629_h__
#define __hustdb_handler_frame_20160413174629_h__

#include "hustdb_handler.h"
#include "hustdb_handler_def.h"

bool hustdb_init_handlers(hustdb_network_ctx_t * ctx, evhtp_t * htp);

#endif // __hustdb_handler_frame_20160413174629_h__