/**
******************************************************************************
* NOTE : Generated by jsoncgen. It is NOT supposed to modify this file.
*****************************************************************************/
#include "message_queue_def.h"

void cjson_dispose_hustmqhamessagequeue(HustmqHaMessageQueue * obj_val)
{
    if (obj_val)
    {
        cjson_dispose_integer(&obj_val->type);
        cjson_dispose_string(&obj_val->queue);
        cjson_dispose_integerarray(&obj_val->ready);
        cjson_dispose_integer(&obj_val->max);
        cjson_dispose_integer(&obj_val->lock);
        cjson_dispose_integer(&obj_val->si);
        cjson_dispose_integer(&obj_val->ci);
        cjson_dispose_integer(&obj_val->tm);
        cjson_dispose_integer(&obj_val->unacked);
        cjson_dispose_integer(&obj_val->timeout);
    }
}

json_bool_t cjson_deserialize_hustmqhamessagequeue(const json_t * json_val, HustmqHaMessageQueue * obj_val)
{
    if (!obj_val || !json_is_object(json_val))
    {
        return false;
    }

    json_t * tmp_json_val = NULL;
    do
    {
        tmp_json_val = json_object_get_field(json_val, "type");
        obj_val->json_has_type = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->type)) break;
        tmp_json_val = json_object_get_field(json_val, "queue");
        obj_val->json_has_queue = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_string(tmp_json_val, &obj_val->queue)) break;
        tmp_json_val = json_object_get_field(json_val, "ready");
        obj_val->json_has_ready = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integerarray(tmp_json_val, &obj_val->ready)) break;
        tmp_json_val = json_object_get_field(json_val, "max");
        obj_val->json_has_max = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->max)) break;
        tmp_json_val = json_object_get_field(json_val, "lock");
        obj_val->json_has_lock = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->lock)) break;
        tmp_json_val = json_object_get_field(json_val, "si");
        obj_val->json_has_si = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->si)) break;
        tmp_json_val = json_object_get_field(json_val, "ci");
        obj_val->json_has_ci = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->ci)) break;
        tmp_json_val = json_object_get_field(json_val, "tm");
        obj_val->json_has_tm = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->tm)) break;
        tmp_json_val = json_object_get_field(json_val, "unacked");
        obj_val->json_has_unacked = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->unacked)) break;
        tmp_json_val = json_object_get_field(json_val, "timeout");
        obj_val->json_has_timeout = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integer(tmp_json_val, &obj_val->timeout)) break;

        return true;
    } while (0);

    return false;
}

json_bool_t cjson_load_hustmqhamessagequeue(const char * input, HustmqHaMessageQueue * obj_val)
{
    json_t * json_val = json_load_from_str(input);
    if (!json_val)
    {
        return false;
    }
    json_bool_t result = cjson_deserialize_hustmqhamessagequeue(json_val, obj_val);
    cjson_dispose_json_value(json_val);
    return result;
}

void cjson_dispose_hustmqhamessagequeuearray(HustmqHaMessageQueueArray * obj_val)
{
    if (!obj_val || !obj_val->arr)
    {
        return;
    }
    size_t index;
    for (index = 0; index < obj_val->size; ++index)
    {
        cjson_dispose_hustmqhamessagequeue(&obj_val->arr[index]);
    }
    json_free(obj_val->arr);
    obj_val->arr = NULL;
    obj_val->size = 0;
}

json_bool_t cjson_deserialize_hustmqhamessagequeuearray(const json_t * json_val, HustmqHaMessageQueueArray * obj_val)
{
    if (!json_is_array(json_val) || !obj_val)
    {
        return false;
    }
    obj_val->size = json_array_size(json_val);
    if (obj_val->size < 1)
    {
        obj_val->arr = NULL;
        return true;
    }
    obj_val->arr = json_malloc(sizeof(HustmqHaMessageQueue) * obj_val->size);
    memset(obj_val->arr, 0, sizeof(HustmqHaMessageQueue) * obj_val->size);
    size_t index;
    for (index = 0; index < obj_val->size; ++index)
    {
        json_t * tmp_json_val = json_array_get_item(json_val, index);
        if (!cjson_deserialize_hustmqhamessagequeue(tmp_json_val, &obj_val->arr[index]))
        {
            cjson_dispose_hustmqhamessagequeuearray(obj_val);
            return false;
        }
    }
    return true;
}

json_bool_t cjson_load_hustmqhamessagequeuearray(const char * input, HustmqHaMessageQueueArray * obj_val)
{
    json_t * json_val = json_load_from_str(input);
    if (!json_val)
    {
        return false;
    }
    json_bool_t result = cjson_deserialize_hustmqhamessagequeuearray(json_val, obj_val);
    cjson_dispose_json_value(json_val);
    return result;
}
