/**
******************************************************************************
* NOTE : Generated by jsoncgen. It is NOT supposed to modify this file.
*****************************************************************************/
#ifndef __worker_def_20151209131531_h__
#define __worker_def_20151209131531_h__

#include "cjson_serialization.h"

typedef struct
{
    json_str_t w;
    json_int_t t;
    json_bool_t json_has_w;
    json_bool_t json_has_t;
} HustmqWorker;

typedef struct
{
    HustmqWorker * arr;
    size_t size;
} HustmqWorkerArray;

void cjson_dispose_hustmqworker(HustmqWorker * obj_val);
json_bool_t cjson_deserialize_hustmqworker(const json_t * json_val, HustmqWorker * obj_val);
json_bool_t cjson_load_hustmqworker(const char * input, HustmqWorker * obj_val);

void cjson_dispose_hustmqworkerarray(HustmqWorkerArray * obj_val);
json_bool_t cjson_deserialize_hustmqworkerarray(const json_t * json_val, HustmqWorkerArray * obj_val);
json_bool_t cjson_load_hustmqworkerarray(const char * input, HustmqWorkerArray * obj_val);


#endif // __worker_def_20151209131531_h__