////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by libevhtp.py. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __sync_handler_frame_20160531152914_h__
#define __sync_handler_frame_20160531152914_h__

#include "sync_handler.h"
#include "sync_handler_def.h"

bool sync_init_handlers(sync_network_ctx_t * ctx, evhtp_t * htp);

#endif // __sync_handler_frame_20160531152914_h__