////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by libevhtp.py. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#include "sync_handler_frame.h"

void sync_status_frame(evhtp_request_t * request, void * data)
{
    sync_network_ctx_t * ctx = reinterpret_cast<sync_network_ctx_t *>(data);
    if (!request || !ctx)
    {
        evhtp::send_reply(EVHTP_RES_500, request);
        return;
    }
    if (!evhtp::check_auth(request, &ctx->base))
    {
        return;
    }
    htp_method method = evhtp_request_get_method(request);
    if (htp_method_GET != method)
    {
        evhtp::invalid_method(request);
        return;
    }
    sync_status_ctx_t args(request->uri->query);
    if (!args.has_backend_count)
    {
        evhtp::send_reply(EVHTP_RES_NOTFOUND, request);
        return;
    }
    sync_status_handler(args, request, ctx);
}

bool sync_init_handlers(sync_network_ctx_t * ctx, evhtp_t * htp)
{
    if (!evhtp_set_cb(htp, "/sync_status", sync_status_frame, ctx)) return false;

    return true;
}