////////////////////////////////////////////////////////////////////////////////
// NOTE : Generated by libevhtp.py. It is NOT supposed to modify this file.
////////////////////////////////////////////////////////////////////////////////
#ifndef __sync_handler_20160531152914_h__
#define __sync_handler_20160531152914_h__

#include "sync_handler_def.h"

void sync_status_handler(const sync_status_ctx_t& args, evhtp_request_t * request, sync_network_ctx_t * ctx);

#endif // __sync_handler_20160531152914_h__