/**
 ******************************************************************************
 * NOTE : Generated by cppgen. It is NOT supposed to modify this file.
 *****************************************************************************/
#include "../lib/status_serialization.h"

namespace json_lib
{

    Status::Status ( )
    {
        // fields from json_lib::Status
        json_has_total_status = false;
        json_has_status = false;
    }

    bool Status::operator== ( const Status& obj ) const
    {
        // fields from json_lib::Status
        if ( ! ( total_status == obj.total_status ) ) return false;
        if ( ! ( status == obj.status ) ) return false;

        return true;
    }

} // json_lib

namespace json_lib
{

    /*
     * generate from "status_serialization.json": "json_lib::Status"
     */
    bool Serialize ( const json_lib::Status& obj_val, Json::Value& json_val )
    {
        do
        {
            // fields from "json_lib::Status"
            if ( ! Serialize (obj_val.total_status, "total_status", json_val) ) break; // @(field_type : std::map<std::string, uint64_t>)
            if ( ! Serialize (obj_val.status, "status", json_val) ) break; // @(field_type : std::map<std::string, std::map<std::string, uint64_t> >)

            return true;
        }
        while ( 0 );

        return false;
    }

    bool Deserialize ( const Json::Value& json_val, json_lib::Status& obj_val )
    {
        do
        {
            // fields from "json_lib::Status"
            if ( ! Deserialize (json_val, "total_status", obj_val.total_status, obj_val.json_has_total_status) ) break; // @(field_type : std::map<std::string, uint64_t>)
            if ( ! Deserialize (json_val, "status", obj_val.status, obj_val.json_has_status) ) break; // @(field_type : std::map<std::string, std::map<std::string, uint64_t> >)

            return true;
        }
        while ( 0 );

        return false;
    }

} // json_lib