/**
******************************************************************************
* NOTE : Generated by jsoncgen. It is NOT supposed to modify this file.
*****************************************************************************/
#ifndef __cjson_serialization_20151209121211_h__
#define __cjson_serialization_20151209121211_h__

#include "cjson_serialization_base.h"

typedef struct
{
    json_int_t * arr;
    size_t size;
} IntegerArray;


json_bool_t cjson_set_integerarray(const IntegerArray * src, IntegerArray * des);
json_bool_t cjson_eq_integerarray(const IntegerArray * src, IntegerArray * des);
void cjson_dispose_integerarray(IntegerArray * obj_val);
json_t * cjson_serialize_integerarray(const IntegerArray * obj_val);
json_bool_t cjson_deserialize_integerarray(const json_t * json_val, IntegerArray * obj_val);
char * cjson_dump_integerarray(const IntegerArray * obj_val);
json_bool_t cjson_load_integerarray(const char * input, IntegerArray * obj_val);
json_bool_t cjson_save_integerarray_to_file(const IntegerArray * obj_val, const char * path);
json_bool_t cjson_load_integerarray_from_file(const char * path, IntegerArray * obj_val);

typedef struct
{
    json_str_t * arr;
    size_t size;
} StringArray;


json_bool_t cjson_set_stringarray(const StringArray * src, StringArray * des);
json_bool_t cjson_eq_stringarray(const StringArray * src, StringArray * des);
void cjson_dispose_stringarray(StringArray * obj_val);
json_t * cjson_serialize_stringarray(const StringArray * obj_val);
json_bool_t cjson_deserialize_stringarray(const json_t * json_val, StringArray * obj_val);
char * cjson_dump_stringarray(const StringArray * obj_val);
json_bool_t cjson_load_stringarray(const char * input, StringArray * obj_val);
json_bool_t cjson_save_stringarray_to_file(const StringArray * obj_val, const char * path);
json_bool_t cjson_load_stringarray_from_file(const char * path, StringArray * obj_val);

typedef struct
{
    double * arr;
    size_t size;
} DoubleArray;


json_bool_t cjson_set_doublearray(const DoubleArray * src, DoubleArray * des);
json_bool_t cjson_eq_doublearray(const DoubleArray * src, DoubleArray * des);
void cjson_dispose_doublearray(DoubleArray * obj_val);
json_t * cjson_serialize_doublearray(const DoubleArray * obj_val);
json_bool_t cjson_deserialize_doublearray(const json_t * json_val, DoubleArray * obj_val);
char * cjson_dump_doublearray(const DoubleArray * obj_val);
json_bool_t cjson_load_doublearray(const char * input, DoubleArray * obj_val);
json_bool_t cjson_save_doublearray_to_file(const DoubleArray * obj_val, const char * path);
json_bool_t cjson_load_doublearray_from_file(const char * path, DoubleArray * obj_val);


#endif // __cjson_serialization_20151209121211_h__