/**
******************************************************************************
* NOTE : Generated by cppgen. It is NOT supposed to modify this file.
*****************************************************************************/
#ifndef __sync_status_20160602114928_h__
#define __sync_status_20160602114928_h__

#include <limits.h>
#include <string>
#include <vector>
#include "json_serialization.h"

namespace jos_lib
{
    struct Status
    {
        std::map<std::string, int> total_status;
        std::map<std::string, std::map<std::string, int> > status;
        bool json_has_total_status;
        bool json_has_status;
        Status();
        bool operator==(const Status& obj) const;
    };
}

namespace jos_lib
{
    bool Serialize(const jos_lib::Status& obj_val, jos_lib::Allocator& alloc, rapidjson::Value& json_val);
    bool Deserialize(const rapidjson::Value& json_val, jos_lib::Status& obj_val);
}

#endif // __sync_status_20160602114928_h__