/**
******************************************************************************
* NOTE : Generated by jsoncgen. It is NOT supposed to modify this file.
*****************************************************************************/
#ifndef __hustdb_ha_def_20160127182752_h__
#define __hustdb_ha_def_20160127182752_h__

#include "cjson_serialization.h"

typedef struct
{
    IntegerArray key;
    StringArray val;
    json_bool_t json_has_key;
    json_bool_t json_has_val;
} HustDbHaTablePair;

void cjson_dispose_hustdbhatablepair(HustDbHaTablePair * obj_val);
json_bool_t cjson_deserialize_hustdbhatablepair(const json_t * json_val, HustDbHaTablePair * obj_val);


typedef struct
{
    HustDbHaTablePair low;
    HustDbHaTablePair high;
    json_bool_t json_has_low;
    json_bool_t json_has_high;
} HustDbHaTableIncr;

void cjson_dispose_hustdbhatableincr(HustDbHaTableIncr * obj_val);
json_bool_t cjson_deserialize_hustdbhatableincr(const json_t * json_val, HustDbHaTableIncr * obj_val);


typedef struct
{
    json_str_t remove;
    json_str_t replace_by;
    json_bool_t json_has_remove;
    json_bool_t json_has_replace_by;
} HustDbHaTableDecr;

void cjson_dispose_hustdbhatabledecr(HustDbHaTableDecr * obj_val);
json_bool_t cjson_deserialize_hustdbhatabledecr(const json_t * json_val, HustDbHaTableDecr * obj_val);


typedef struct
{
    HustDbHaTablePair item;
    HustDbHaTableIncr increase;
    HustDbHaTableDecr decrease;
    json_bool_t json_has_item;
    json_bool_t json_has_increase;
    json_bool_t json_has_decrease;
} HustDbHaTableElem;

typedef struct
{
    HustDbHaTableElem * arr;
    size_t size;
} HustDbHaTableElemArray;

void cjson_dispose_hustdbhatableelem(HustDbHaTableElem * obj_val);
json_bool_t cjson_deserialize_hustdbhatableelem(const json_t * json_val, HustDbHaTableElem * obj_val);

void cjson_dispose_hustdbhatableelemarray(HustDbHaTableElemArray * obj_val);
json_bool_t cjson_deserialize_hustdbhatableelemarray(const json_t * json_val, HustDbHaTableElemArray * obj_val);

typedef struct
{
    HustDbHaTableElemArray table;
    json_bool_t json_has_table;
} HustDbHaTable;

void cjson_dispose_hustdbhatable(HustDbHaTable * obj_val);
json_bool_t cjson_deserialize_hustdbhatable(const json_t * json_val, HustDbHaTable * obj_val);
json_bool_t cjson_load_hustdbhatable_from_file(const char * path, HustDbHaTable * obj_val);



#endif // __hustdb_ha_def_20160127182752_h__