/**
******************************************************************************
* NOTE : Generated by jsoncgen. It is NOT supposed to modify this file.
*****************************************************************************/
#include "hustdb_ha_def.h"

void cjson_dispose_hustdbhatablepair(HustDbHaTablePair * obj_val)
{
    if (obj_val)
    {
        cjson_dispose_integerarray(&obj_val->key);
        cjson_dispose_stringarray(&obj_val->val);
    }
}

json_bool_t cjson_deserialize_hustdbhatablepair(const json_t * json_val, HustDbHaTablePair * obj_val)
{
    if (!obj_val || !json_is_object(json_val))
    {
        return false;
    }

    json_t * tmp_json_val = NULL;
    do
    {
        tmp_json_val = json_object_get_field(json_val, "key");
        obj_val->json_has_key = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_integerarray(tmp_json_val, &obj_val->key)) break;
        tmp_json_val = json_object_get_field(json_val, "val");
        obj_val->json_has_val = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_stringarray(tmp_json_val, &obj_val->val)) break;

        return true;
    } while (0);

    return false;
}

void cjson_dispose_hustdbhatableincr(HustDbHaTableIncr * obj_val)
{
    if (obj_val)
    {
        cjson_dispose_hustdbhatablepair(&obj_val->low);
        cjson_dispose_hustdbhatablepair(&obj_val->high);
    }
}

json_bool_t cjson_deserialize_hustdbhatableincr(const json_t * json_val, HustDbHaTableIncr * obj_val)
{
    if (!obj_val || !json_is_object(json_val))
    {
        return false;
    }

    json_t * tmp_json_val = NULL;
    do
    {
        tmp_json_val = json_object_get_field(json_val, "low");
        obj_val->json_has_low = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_hustdbhatablepair(tmp_json_val, &obj_val->low)) break;
        tmp_json_val = json_object_get_field(json_val, "high");
        obj_val->json_has_high = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_hustdbhatablepair(tmp_json_val, &obj_val->high)) break;

        return true;
    } while (0);

    return false;
}

void cjson_dispose_hustdbhatabledecr(HustDbHaTableDecr * obj_val)
{
    if (obj_val)
    {
        cjson_dispose_string(&obj_val->remove);
        cjson_dispose_string(&obj_val->replace_by);
    }
}

json_bool_t cjson_deserialize_hustdbhatabledecr(const json_t * json_val, HustDbHaTableDecr * obj_val)
{
    if (!obj_val || !json_is_object(json_val))
    {
        return false;
    }

    json_t * tmp_json_val = NULL;
    do
    {
        tmp_json_val = json_object_get_field(json_val, "remove");
        obj_val->json_has_remove = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_string(tmp_json_val, &obj_val->remove)) break;
        tmp_json_val = json_object_get_field(json_val, "replace_by");
        obj_val->json_has_replace_by = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_string(tmp_json_val, &obj_val->replace_by)) break;

        return true;
    } while (0);

    return false;
}

void cjson_dispose_hustdbhatableelem(HustDbHaTableElem * obj_val)
{
    if (obj_val)
    {
        cjson_dispose_hustdbhatablepair(&obj_val->item);
        cjson_dispose_hustdbhatableincr(&obj_val->increase);
        cjson_dispose_hustdbhatabledecr(&obj_val->decrease);
    }
}

json_bool_t cjson_deserialize_hustdbhatableelem(const json_t * json_val, HustDbHaTableElem * obj_val)
{
    if (!obj_val || !json_is_object(json_val))
    {
        return false;
    }

    json_t * tmp_json_val = NULL;
    do
    {
        tmp_json_val = json_object_get_field(json_val, "item");
        obj_val->json_has_item = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_hustdbhatablepair(tmp_json_val, &obj_val->item)) break;
        tmp_json_val = json_object_get_field(json_val, "increase");
        obj_val->json_has_increase = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_hustdbhatableincr(tmp_json_val, &obj_val->increase)) break;
        tmp_json_val = json_object_get_field(json_val, "decrease");
        obj_val->json_has_decrease = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_hustdbhatabledecr(tmp_json_val, &obj_val->decrease)) break;

        return true;
    } while (0);

    return false;
}

void cjson_dispose_hustdbhatableelemarray(HustDbHaTableElemArray * obj_val)
{
    if (!obj_val || !obj_val->arr)
    {
        return;
    }
    size_t index;
    for (index = 0; index < obj_val->size; ++index)
    {
        cjson_dispose_hustdbhatableelem(&obj_val->arr[index]);
    }
    json_free(obj_val->arr);
    obj_val->arr = NULL;
    obj_val->size = 0;
}

json_bool_t cjson_deserialize_hustdbhatableelemarray(const json_t * json_val, HustDbHaTableElemArray * obj_val)
{
    if (!json_is_array(json_val) || !obj_val)
    {
        return false;
    }
    obj_val->size = json_array_size(json_val);
    if (obj_val->size < 1)
    {
        obj_val->arr = NULL;
        return true;
    }
    obj_val->arr = json_malloc(sizeof(HustDbHaTableElem) * obj_val->size);
    memset(obj_val->arr, 0, sizeof(HustDbHaTableElem) * obj_val->size);
    size_t index;
    for (index = 0; index < obj_val->size; ++index)
    {
        json_t * tmp_json_val = json_array_get_item(json_val, index);
        if (!cjson_deserialize_hustdbhatableelem(tmp_json_val, &obj_val->arr[index]))
        {
            cjson_dispose_hustdbhatableelemarray(obj_val);
            return false;
        }
    }
    return true;
}

void cjson_dispose_hustdbhatable(HustDbHaTable * obj_val)
{
    if (obj_val)
    {
        cjson_dispose_hustdbhatableelemarray(&obj_val->table);
    }
}

json_bool_t cjson_deserialize_hustdbhatable(const json_t * json_val, HustDbHaTable * obj_val)
{
    if (!obj_val || !json_is_object(json_val))
    {
        return false;
    }

    json_t * tmp_json_val = NULL;
    do
    {
        tmp_json_val = json_object_get_field(json_val, "table");
        obj_val->json_has_table = !!tmp_json_val;
        if (tmp_json_val && !cjson_deserialize_hustdbhatableelemarray(tmp_json_val, &obj_val->table)) break;

        return true;
    } while (0);

    return false;
}

json_bool_t cjson_load_hustdbhatable_from_file(const char * path, HustDbHaTable * obj_val)
{
    json_t * json_val = json_load_from_file(path);
    if (!json_val)
    {
        return false;
    }
    json_bool_t result = cjson_deserialize_hustdbhatable(json_val, obj_val);
    cjson_dispose_json_value(json_val);
    return result;
}
