/**
 ******************************************************************************
 * NOTE : Generated by cppgen. It is NOT supposed to modify this file.
 *****************************************************************************/
#ifndef __status_serialization_20151216165651_h__
#define __status_serialization_20151216165651_h__

#include <map>
#include <string>
//#include "sample_enum.h"
#include "json_serialization.h"
#include <stdint.h>

namespace json_lib
{

    struct Status
    {
        std::map<std::string, int> total_status;
        std::map<std::string, std::map<std::string, int> > status;
        bool json_has_total_status;
        bool json_has_status;
        Status ( );
        bool operator== ( const Status& obj ) const;
    };
}

namespace json_lib
{
    bool Serialize ( const json_lib::Status& obj_val, Json::Value& json_val );
    bool Deserialize ( const Json::Value& json_val, json_lib::Status& obj_val );
}

#endif // __status_serialization_20151216165651_h__